apiVersion: v1
kind: PersistentVolume
metadata:
  name: healthmed-api-database-pv
spec:
  capacity:
    storage: 10Gi  # Specify the storage size
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # Keep data even if the PVC is deleted
  hostPath:
    path: "/mnt/data"  # Use this for local testing or development; change it to a cloud storage solution in production
